### ISSUE TITLE
2021.3.2 compatibility?

### ISSUE THREAD

**Issue by colindean** [smashedtoatoms/zenburn#3]
I've kept around a jarfile with a theme for a long time and am super happy to see that someone finally published a proper plugin!

Any chance you could release a version with `2021.3.2` compatibility?

**Comment by smashedtoatoms** [comment]
I am not sure I'd call it proper.  I had been doing the same thing and then spun this off.  Apparently, the dependabot config hasn't been running so none of the auto-publishing stuff has been working.  I just manually updated the dependencies to see if that will publish what it is supposed to.  It's pending review [here](https://plugins.jetbrains.com/plugin/17938-zenburn/versions/stable/156811) and should be available tomorrow based on my previous examples with this process.  Thanks for opening this ticket.  It has been borked for months and I had no idea.
