### ISSUE TITLE
please update the plugin

### ISSUE THREAD

**Issue by ukaszg** [smashedtoatoms/zenburn#4]
Hi, I can't find the plugin in marketplace, when installing from disk I get an error:

> Plugin 'Zenburn' (version '0.0.7') is not compatible with the current version of the IDE, because it requires build 213.* or older but the current build is IU-221.5921.22

**Comment by CristianoPizzamiglio** [comment]
Still unresolved. I hope it will be available for the newer versions of PyCharm very soon.

**Comment by smashedtoatoms** [comment]
Oh no!  I am so sorry everyone.  My github notifications were borked until about a month ago so I just saw this.  This is pending approval and can be downloaded [here](https://plugins.jetbrains.com/plugin/17938-zenburn/versions/stable/229596) if you need it immediately.  It will be available on Jetbrains website by Friday.

**Comment by CristianoPizzamiglio** [comment]
That's a good news! Thanks!

**Comment by ikr** [comment]
v0.0.9 is incompatible with the latest IntelliJ IDEA 2023.1 now.

> Incompatible: requires IDE build 223.* or earlier

**Comment by smashedtoatoms** [comment]
This has been built and will be available after review (24 hours typically).

It can be found here in the meantime: https://plugins.jetbrains.com/plugin/17938-zenburn/versions/stable/313978
