### ISSUE TITLE
v0.1.0 → v0.1.1 update in latest IntelliJ CE broke the theme

### ISSUE THREAD

**Issue by ikr** [smashedtoatoms/zenburn#6]
It's all white now, with dark text.

**Comment by ikr** [comment]
My bad, sorry. Figured it out.

**Comment by smashedtoatoms** [comment]
Mine did this too!  When it updates, it flips to a light theme.  I am still trying to understand why.  This version of Intellij also changed the way my clipboard works with IdeaVim.  In any case, setting the color scheme to Zenburn fixed it for me.  Sorry.  I don't know what I can do to make this not happen.

**Comment by ikr** [comment]
Right! What helped in my case, was a "reset to defaults" for the theme.

Thanks a lot for the IntelliJ plugin btw, @smashedtoatoms ! Zenburn is the best; use it in all my editors.

**Comment by rni063** [comment]
I tried to set and reset the theme, but it's still broken for me. I'm running Rider 2023.2.2.

Any additional tips to fix this? I really don't want to use any other themes.

**Comment by rni063** [comment]
Downgrading Rider to 2023.1.4 solved the issue for me.
