### ISSUE TITLE
Defaults to regular light theme

### ISSUE THREAD

**Issue by MagnusMalmqvist** [smashedtoatoms/zenburn#8]
Using Rider 2024.2.7 and Zenburn plugin version 0.1.6 
Also tested with some 2023 version of Rider (don't recall exatly which one) and had the same issue

![image](https://github.com/user-attachments/assets/62bb5443-fcee-4be7-bae7-56824df86866)

Attempted to play around with the different settings, but it didnt change this appearance

**Comment by smashedtoatoms** [comment]
Are you on Windows or Mac?  I've been using this as my daily driver on two Windows 11 machines and one Mac for the last 2 years and have had this happen sometimes after upgrades, but never permanently.  I have no idea why. If I uninstall and reinstall the plugin, it fixes it. I've also had some luck switching to a different theme and back. As far as I can tell, it is not the plugin itself, and I can't reliably replicate it.

**Comment by MagnusMalmqvist** [comment]
On windows 11, this happened when I upgraded the plugin from version 0.1.1 to 0.1.5 - I was using some version of Rider 2023 then, so I updated Rider and the plugin to 0.1.6 but the issue persisted. 

I uninstalled, restarted Rider, reinstalled and Restarted Rider again, but still light theme. It might be some setting or conflict on my end if yours works. I will look and see if I find anything.

**Comment by smashedtoatoms** [comment]
That is incredibly frustrating.  I'm sorry.  My Windows install seems to flip to all white every time it does a major release.  The last time it did it, I only had to go in, choose the default dark theme, and then flip it back and then go into the editor preferences themselves and choose the Zenburn theme again.  I didn't have to re-install it completely, but I basically had to choose Zenburn in every place I could.  Oddly enough, it doesn't happen on my Mac.  I am running the latest of everything and a pretty minimal set of plugins.

**Comment by MagnusMalmqvist** [comment]
No worries, I will test that. The only plugins I have are zeburn, monokai and darkburn. I will also attempt to remove all other plugins and add one by one and see if that changes.

**Comment by MagnusMalmqvist** [comment]
Ok, that seems to have solved it!. I flipped it to default dark, and then back and my beloved zenburn is back : ) 

Thank you for the help, I love this theme

**Comment by smashedtoatoms** [comment]
Awesome!  Sorry about that. Whenever I figure out why it does that I will fix it.
